// src/lib/components/Card.svelte
<script lang="ts">
	import type { Card as CardType } from '$types/game';
	import { getCardColor } from '$utils/helpers';
	
	export let card: CardType;
	export let isHidden = false;
	export let isPlayable = false;
	export let isSelected = false;
	export let size: 'small' | 'medium' | 'large' = 'medium';
	export let onClick: (() => void) | undefined = undefined;
	
	// Size classes
	const sizeClasses = {
		small: 'w-16 h-24 text-sm',
		medium: 'w-20 h-32 text-base',
		large: 'w-24 h-36 text-lg'
	};
	
	// Card color
	$: cardColor = getCardColor(card.suit);
	$: colorClass = cardColor === 'red' ? 'text-red-500' : 'text-gray-900';
	
	function handleClick() {
		if (isPlayable && onClick) {
			onClick();
		}
	}
</script>

<button
	class="card {sizeClasses[size]} {isPlayable ? 'playable' : ''} {isHidden ? 'hidden-card' : ''} {isSelected ? 'selected' : ''}"
	on:click={handleClick}
	disabled={!isPlayable}
	type="button"
>
	{#if isHidden}
		<!-- Card Back -->
		<div class="card-back">
			<div class="card-pattern"></div>
		</div>
	{:else}
		<!-- Card Front -->
		<div class="card-front">
			<!-- Top Left Corner -->
			<div class="corner top-left {colorClass}">
				<div class="rank">{card.rank}</div>
				<div class="suit">{card.suit}</div>
			</div>
			
			<!-- Center Suit -->
			<div class="center-suit {colorClass}">
				{card.suit}
			</div>
			
			<!-- Bottom Right Corner (rotated) -->
			<div class="corner bottom-right {colorClass}">
				<div class="rank">{card.rank}</div>
				<div class="suit">{card.suit}</div>
			</div>
		</div>
	{/if}
</button>

<style>
	.card {
		position: relative;
		border-radius: 0.5rem;
		background: white;
		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
		transition: all 0.3s ease;
		cursor: default;
		border: 2px solid #e5e7eb;
		overflow: hidden;
	}
	
	.card:not(.hidden-card) {
		animation: card-deal 0.5s ease-out;
	}
	
	.card.playable {
		cursor: pointer;
		border-color: #10b981;
	}
	
	.card.playable:hover {
		transform: translateY(-8px) scale(1.05);
		box-shadow: 0 12px 24px rgba(16, 185, 129, 0.3);
		border-color: #059669;
	}
	
	.card.playable:active {
		transform: translateY(-4px) scale(1.02);
	}
	
	.card:disabled {
		cursor: not-allowed;
	}
	
	/* Card Back */
	.card-back {
		width: 100%;
		height: 100%;
		background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		position: relative;
	}
	
	.card-pattern {
		width: 80%;
		height: 80%;
		background-image: 
			repeating-linear-gradient(45deg, transparent, transparent 10px, rgba(255,255,255,0.1) 10px, rgba(255,255,255,0.1) 20px),
			repeating-linear-gradient(-45deg, transparent, transparent 10px, rgba(255,255,255,0.1) 10px, rgba(255,255,255,0.1) 20px);
		border: 2px solid rgba(255, 255, 255, 0.3);
		border-radius: 0.25rem;
	}
	
	/* Card Front */
	.card-front {
		width: 100%;
		height: 100%;
		padding: 0.5rem;
		position: relative;
		background: white;
	}
	
	.corner {
		position: absolute;
		display: flex;
		flex-direction: column;
		align-items: center;
		font-weight: bold;
		line-height: 1;
	}
	
	.corner.top-left {
		top: 0.25rem;
		left: 0.25rem;
	}
	
	.corner.bottom-right {
		bottom: 0.25rem;
		right: 0.25rem;
		transform: rotate(180deg);
	}
	
	.rank {
		font-size: 1.25em;
		margin-bottom: 0.1em;
	}
	
	.suit {
		font-size: 1em;
	}
	
	.center-suit {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		font-size: 2.5em;
		font-weight: bold;
		opacity: 0.3;
	}
	
	/* Animations */
	@keyframes card-deal {
		from {
			opacity: 0;
			transform: translateY(-20px) rotateY(90deg);
		}
		to {
			opacity: 1;
			transform: translateY(0) rotateY(0deg);
		}
	}
	
	/* Hidden card animation */
	.hidden-card {
		animation: card-flip 0.6s ease-in-out;
	}
	
	@keyframes card-flip {
		0% {
			transform: rotateY(0deg);
		}
		50% {
			transform: rotateY(90deg);
		}
		100% {
			transform: rotateY(0deg);
		}
	}
	
	/* Responsive sizing */
	@media (max-width: 640px) {
		.card {
			transform-origin: center;
		}
		
		.card.playable:hover {
			transform: translateY(-4px) scale(1.02);
		}
	}
</style>

// components/Card.tsx
import React from 'react'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import { Crown, Star, Sparkles } from 'lucide-react'

interface CardProps {
  card: {
    id: string
    suit: string
    rank: string
  }
  onClick?: (card: any) => void
  disabled?: boolean
  selected?: boolean
  highlighted?: boolean
  size?: 'small' | 'normal' | 'large'
  showPoints?: boolean
  isPlayable?: boolean
  isHidden?: boolean
}

export function Card({ 
  card, 
  onClick, 
  disabled = false, 
  selected = false, 
  highlighted = false, 
  size = 'normal',
  showPoints = true
}: CardProps) {
  if (!card) {
    return (
      <div className={`
        ${size === 'small' ? 'w-12 h-16' : size === 'large' ? 'w-20 h-28' : 'w-16 h-24'}
        bg-gradient-to-br from-gray-50 to-gray-100 
        border-2 border-dashed border-gray-300 
        rounded-xl flex items-center justify-center
        transition-all duration-300 hover:border-gray-400
        shadow-inner
      `}>
        <div className="text-gray-400 text-xs font-medium">Empty</div>
      </div>
    )
  }

  const getSuitSymbol = (suit: string) => {
    switch (suit) {
      case 'hearts': return '♥'
      case 'diamonds': return '♦'
      case 'clubs': return '♣'
      case 'spades': return '♠'
      default: return suit
    }
  }

  const getSuitColor = (suit: string) => {
    return suit === 'hearts' || suit === 'diamonds' 
      ? 'text-casino-red' 
      : 'text-gray-800'
  }

  const getSuitGradient = (suit: string) => {
    switch (suit) {
      case 'hearts': 
        return 'from-casino-red-light to-casino-red-dark'
      case 'diamonds': 
        return 'from-casino-blue-light to-casino-blue-dark'
      case 'clubs': 
        return 'from-gray-700 to-gray-900'
      case 'spades': 
        return 'from-gray-800 to-black'
      default: 
        return 'from-gray-600 to-gray-800'
    }
  }

  const getCardValue = (rank: string) => {
    switch (rank) {
      case 'A': return 1
      case 'J': return 11
      case 'Q': return 12
      case 'K': return 13
      default: return parseInt(rank) || 0
    }
  }

  const isSpecialCard = () => {
    return (
      rank === 'A' || // All Aces
      (suit === 'spades' && rank === '2') || // 2 of Spades
      (suit === 'diamonds' && rank === '10') // 10 of Diamonds
    )
  }

  const getCardPoints = () => {
    if (rank === 'A') return 1
    if (suit === 'spades' && rank === '2') return 1
    if (suit === 'diamonds' && rank === '10') return 2
    return 0
  }

  const { suit, rank } = card
  const suitSymbol = getSuitSymbol(suit)
  const suitColor = getSuitColor(suit)
  const suitGradient = getSuitGradient(suit)
  const points = getCardPoints()
  const special = isSpecialCard()

  const sizeClasses = {
    small: 'w-12 h-16 text-xs',
    normal: 'w-16 h-24 text-sm',
    large: 'w-20 h-28 text-base'
  }

  const cardContent = (
    <div className={`
      ${sizeClasses[size]}
      relative bg-gradient-to-br from-white via-gray-50 to-white
      rounded-xl shadow-lg border-2 
      transition-all duration-300 ease-out
      card-hover
      ${selected 
        ? 'border-casino-gold ring-4 ring-casino-gold/30 shadow-glow-gold transform -translate-y-2 shadow-2xl' 
        : highlighted 
        ? 'border-casino-blue ring-3 ring-casino-blue/30 shadow-casino' 
        : special
        ? 'border-casino-purple/40 shadow-casino hover:border-casino-purple'
        : 'border-gray-200 hover:border-gray-300 hover:shadow-casino'
      }
      ${disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}
      ${onClick ? 'hover:scale-105 active:scale-95' : ''}
      overflow-hidden
    `}>
      {/* Background pattern for special cards */}
      {special && (
        <div className="absolute inset-0 opacity-5">
          <div className="absolute top-1 right-1">
            <Sparkles className="w-3 h-3" />
          </div>
          <div className="absolute bottom-1 left-1">
            <Sparkles className="w-3 h-3" />
          </div>
        </div>
      )}

      {/* Shimmer effect on hover */}
      <div className="absolute inset-0 shimmer opacity-0 hover:opacity-100 transition-opacity duration-300" />
      
      {/* Main card content */}
      <div className="relative h-full flex flex-col justify-between p-2">
        {/* Top corner - rank and suit */}
        <div className={`flex flex-col items-center ${suitColor} font-bold leading-none`}>
          <div className={`${size === 'small' ? 'text-xs' : 'text-sm'} font-black`}>
            {rank}
          </div>
          <div className={`${size === 'small' ? 'text-xs' : 'text-base'} leading-none mt-0.5 
            bg-gradient-to-br ${suitGradient} bg-clip-text text-transparent font-black`}>
            {suitSymbol}
          </div>
        </div>

        {/* Center suit symbol (for face cards and aces) */}
        {(rank === 'A' || rank === 'K' || rank === 'Q' || rank === 'J') && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className={`
              ${size === 'small' ? 'text-xl' : size === 'large' ? 'text-4xl' : 'text-2xl'} 
              font-black opacity-20
              bg-gradient-to-br ${suitGradient} bg-clip-text text-transparent
            `}>
              {rank === 'A' ? suitSymbol : rank}
            </div>
          </div>
        )}

        {/* Bottom corner - rank and suit (rotated) */}
        <div className={`flex flex-col items-center ${suitColor} font-bold leading-none self-end transform rotate-180`}>
          <div className={`${size === 'small' ? 'text-xs' : 'text-sm'} font-black`}>
            {rank}
          </div>
          <div className={`${size === 'small' ? 'text-xs' : 'text-base'} leading-none mt-0.5 
            bg-gradient-to-br ${suitGradient} bg-clip-text text-transparent font-black`}>
            {suitSymbol}
          </div>
        </div>
      </div>

      {/* Points badge for special cards */}
      {showPoints && points > 0 && (
        <div className="absolute -top-2 -right-2">
          <Badge className={`
            ${size === 'small' ? 'text-xs px-1.5 py-0.5' : 'text-xs px-2 py-1'}
            bg-gradient-to-r from-casino-gold to-casino-gold-dark 
            text-white font-bold shadow-gold border-0
            animate-pulse-slow
          `}>
            {points === 2 ? (
              <div className="flex items-center space-x-0.5">
                <Crown className="w-2.5 h-2.5" />
                <span>{points}</span>
              </div>
            ) : (
              <div className="flex items-center space-x-0.5">
                <Star className="w-2.5 h-2.5" />
                <span>{points}</span>
              </div>
            )}
          </Badge>
        </div>
      )}

      {/* Special card glow effect */}
      {special && selected && (
        <div className="absolute inset-0 bg-gradient-to-br from-casino-gold/20 via-transparent to-casino-purple/20 rounded-xl pointer-events-none" />
      )}
    </div>
  )

  if (onClick && !disabled) {
    return (
      <Button
        variant="ghost"
        className="p-0 h-auto w-auto bg-transparent hover:bg-transparent border-0 shadow-none"
        onClick={() => onClick(card)}
      >
        {cardContent}
      </Button>
    )
  }

  return cardContent
}
