// src/lib/components/RoomManager.svelte
<script lang="ts">
  import { gameStore } from '$stores/gameStore';
  import { connectionStore } from '$stores/connectionStore';
  import {
    createRoom,
    joinRoom,
    joinRandomRoom,
    validatePlayerName,
    validateRoomCode,
    formatRoomCode,
    sanitizePlayerName,
    copyToClipboard,
  } from '$utils';
  import { onMount } from 'svelte';

  // Component state
  let playerName = '';
  let roomCode = '';
  let isCreating = false;
  let isJoining = false;
  let error = '';
  let showRoomCode = false;
  let copied = false;

  // Load saved player name
  onMount(() => {
    const saved = localStorage.getItem('cassino_player_name');
    if (saved) {
      playerName = saved;
    }
  });

  // Reactive validation
  $: playerNameValid = validatePlayerName(playerName).valid;
  $: roomCodeValid = roomCode.length === 0 || validateRoomCode(roomCode).valid;
  $: canCreateOrJoinRandom = playerNameValid && !isCreating && !isJoining;
  $: canJoinRoom =
    playerNameValid && roomCodeValid && roomCode.length === 6 && !isCreating && !isJoining;

  async function handleCreateRoom() {
    error = '';
    isCreating = true;

    try {
      const sanitized = sanitizePlayerName(playerName);
      localStorage.setItem('cassino_player_name', sanitized);

      const response = await createRoom(sanitized);

      gameStore.setRoomId(response.room_id);
      gameStore.setPlayerId(response.player_id);
      gameStore.setPlayerName(sanitized);
      gameStore.setGameState(response.game_state);

      showRoomCode = true;

      // Connect WebSocket
      await connectionStore.connect(response.room_id);
    } catch (err: any) {
      error = err.message || 'Failed to create room';
    } finally {
      isCreating = false;
    }
  }

  async function handleJoinRoom() {
    error = '';
    isJoining = true;

    try {
      const sanitized = sanitizePlayerName(playerName);
      const formatted = formatRoomCode(roomCode);

      localStorage.setItem('cassino_player_name', sanitized);

      const response = await joinRoom(formatted, sanitized);

      gameStore.setRoomId(formatted);
      gameStore.setPlayerId(response.player_id);
      gameStore.setPlayerName(sanitized);
      gameStore.setGameState(response.game_state);

      // Connect WebSocket
      await connectionStore.connect(formatted);
    } catch (err: any) {
      error = err.message || 'Failed to join room';
    } finally {
      isJoining = false;
    }
  }

  async function handleJoinRandom() {
    error = '';
    isJoining = true;

    try {
      const sanitized = sanitizePlayerName(playerName);
      localStorage.setItem('cassino_player_name', sanitized);

      const response = await joinRandomRoom(sanitized);

      gameStore.setRoomId(response.game_state.roomId);
      gameStore.setPlayerId(response.player_id);
      gameStore.setPlayerName(sanitized);
      gameStore.setGameState(response.game_state);

      // Connect WebSocket
      await connectionStore.connect(response.game_state.roomId);
    } catch (err: any) {
      error = err.message || 'Failed to join random room';
    } finally {
      isJoining = false;
    }
  }

  async function handleCopyRoomCode() {
    if ($gameStore.roomId) {
      const success = await copyToClipboard($gameStore.roomId);
      if (success) {
        copied = true;
        setTimeout(() => (copied = false), 2000);
      }
    }
  }

  function handleRoomCodeInput(e: Event) {
    const input = e.target as HTMLInputElement;
    roomCode = formatRoomCode(input.value);
  }
</script>

<div class="room-manager">
  {#if !$gameStore.roomId}
    <!-- Room Creation/Joining UI -->
    <div class="casino-bg backdrop-casino rounded-xl p-8 max-w-md mx-auto shadow-2xl">
      <h1 class="text-4xl font-bold text-center mb-2 text-casino-gold">Casino Card Game</h1>
      <p class="text-center text-gray-300 mb-8">Create or join a game room to start playing</p>

      <!-- Create New Room Section -->
      <section class="mb-6">
        <h2 class="text-2xl font-semibold text-casino-gold mb-4">Create New Room</h2>

        <!-- Player Name Input -->
        <div class="mb-4">
          <label for="playerName" class="block text-sm font-medium text-gray-200 mb-2">
            Your Name
          </label>
          <input
            id="playerName"
            data-testid="player-name-input-create-test"
            type="text"
            bind:value={playerName}
            placeholder="Enter your name"
            maxlength="20"
            class="input-field"
            disabled={isCreating || isJoining}
          />
          {#if playerName && !playerNameValid}
            <p class="text-red-400 text-sm mt-1">
              Name must be 1-20 characters (letters, numbers, spaces only)
            </p>
          {/if}
        </div>

        <!-- Create Room Button -->
        <button
          data-testid="create-room-test"
          on:click={handleCreateRoom}
          disabled={!canCreateOrJoinRandom}
          class="btn-primary w-full mb-4"
        >
          {#if isCreating}
            <span class="inline-block animate-spin mr-2">⚙</span>
            Creating Room...
          {:else}
            🎲 Create Room
          {/if}
        </button>

        <!-- Join Random Button -->
        <button
          data-testid="join-random-test"
          on:click={handleJoinRandom}
          disabled={!canCreateOrJoinRandom}
          class="btn-primary w-full bg-purple-600 hover:bg-purple-700"
        >
          {#if isJoining}
            <span class="inline-block animate-spin mr-2">⚙</span>
            Joining...
          {:else}
            🎯 Quick Match
          {/if}
        </button>
      </section>

      <!-- Divider -->
      <div class="relative mb-6">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-600"></div>
        </div>
        <div class="relative flex justify-center text-sm">
          <span class="px-4 bg-gray-800 text-gray-400">OR</span>
        </div>
      </div>

      <!-- Join Existing Room Section -->
      <section>
        <h2 class="text-2xl font-semibold text-casino-gold mb-4">Join Existing Room</h2>

        <!-- Player Name Input for Join -->
        <div class="mb-4">
          <label for="playerNameJoin" class="block text-sm font-medium text-gray-200 mb-2">
            Your Name
          </label>
          <input
            id="playerNameJoin"
            data-testid="player-name-input-join"
            type="text"
            bind:value={playerName}
            placeholder="Enter your name"
            maxlength="20"
            class="input-field"
            disabled={isCreating || isJoining}
          />
        </div>

        <!-- Join Room Input -->
        <div class="mb-4">
          <label for="roomCode" class="block text-sm font-medium text-gray-200 mb-2">
            Room Code
          </label>
          <input
            id="roomCode"
            data-testid="room-code-input"
            type="text"
            bind:value={roomCode}
            on:input={handleRoomCodeInput}
            placeholder="ABC123"
            maxlength="6"
            class="input-field uppercase"
            disabled={isCreating || isJoining}
          />
          {#if roomCode && !roomCodeValid}
            <p class="text-red-400 text-sm mt-1">Room code must be exactly 6 characters</p>
          {/if}
        </div>

        <!-- Join Room Button -->
        <button
          data-testid="join-room-test"
          on:click={handleJoinRoom}
          disabled={!canJoinRoom}
          class="btn-primary w-full bg-green-600 hover:bg-green-700"
        >
          {#if isJoining}
            <span class="inline-block animate-spin mr-2">⚙</span>
            Joining...
          {:else}
            🚪 Join Room
          {/if}
        </button>
      </section>

      <!-- Error Message -->
      {#if error}
        <div class="mt-4 p-3 bg-red-900/50 border border-red-500 rounded-lg">
          <p class="text-red-200 text-sm">
            ⚠️ {error}
          </p>
        </div>
      {/if}
    </div>
  {:else}
    <!-- Room Created - Show Code -->
    <div class="casino-bg backdrop-casino rounded-xl p-8 max-w-md mx-auto shadow-2xl">
      <h2 class="text-3xl font-bold text-center mb-4 text-casino-gold">Room Created!</h2>

      <p class="text-center text-gray-300 mb-6">Share this code with your opponent:</p>

      <!-- Room Code Display -->
      <div class="bg-gray-900 rounded-lg p-6 mb-6 border-2 border-casino-gold">
        <p class="text-center text-5xl font-bold tracking-widest text-casino-gold">
          {$gameStore.roomId}
        </p>
      </div>

      <!-- Copy Button -->
      <button on:click={handleCopyRoomCode} class="btn-primary w-full mb-4">
        {#if copied}
          ✅ Copied!
        {:else}
          📋 Copy Room Code
        {/if}
      </button>

      <p class="text-center text-gray-400 text-sm">Waiting for opponent to join...</p>

      <!-- Connection Status -->
      <div class="mt-4 text-center">
        {#if $connectionStore.status === 'connected'}
          <span class="text-green-400">🟢 Connected</span>
        {:else if $connectionStore.status === 'connecting'}
          <span class="text-yellow-400">🟡 Connecting...</span>
        {:else}
          <span class="text-red-400">🔴 Disconnected</span>
        {/if}
      </div>
    </div>
  {/if}
</div>

<style>
  .room-manager {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem 1rem;
  }

  /* Additional component-specific styles */
  input:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }

  .animate-spin {
    animation: spin 1s linear infinite;
  }
</style>

// components/RoomManager.tsx
import React, { useState } from 'react'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Label } from './ui/label'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import { Crown, Users, PlayCircle, Shuffle } from 'lucide-react'

interface RoomManagerProps {
  roomId: string
  setRoomId: (roomId: string) => void
  playerName: string
  setPlayerName: (name: string) => void
  onCreateRoom: () => void
  onJoinRoom: (roomId: string, playerName: string) => void
  onJoinRandomRoom?: () => void
  error: string
  isLoading: boolean
}

export function RoomManager({
  roomId,
  setRoomId,
  playerName,
  setPlayerName,
  onCreateRoom,
  onJoinRoom,
  onJoinRandomRoom,
  error,
  isLoading
}: RoomManagerProps) {
  const [showJoinForm, setShowJoinForm] = useState(false)

  const handleJoin = () => {
    if (roomId.trim() && playerName.trim()) {
      onJoinRoom(roomId.trim().toUpperCase(), playerName.trim())
    }
  }

  return (
    <Card className="w-full max-w-md mx-auto bg-gradient-to-br from-slate-800/90 to-slate-900/90 border-2 border-purple-500/30 shadow-2xl" data-testid="room-manager">
      <CardHeader className="text-center pb-4">
        <div className="flex justify-center items-center mb-4">
          <div className="relative">
            <div className="absolute -inset-2 bg-gradient-to-r from-yellow-400 via-purple-500 to-blue-500 rounded-full blur-lg opacity-50" />
            <div className="relative bg-gradient-to-br from-purple-600 to-blue-600 rounded-full p-4">
              <Crown className="w-10 h-10 text-white" />
            </div>
          </div>
        </div>
        <CardTitle className="text-4xl font-black text-white mb-2">Cassino</CardTitle>
        <p className="text-white/80 font-medium">Play the classic card game online</p>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Player Name Input */}
        <div>
          <Label htmlFor="playerName" className="text-white/90 mb-2 block">Your Name</Label>
          <Input
            id="playerName"
            type="text"
            value={playerName}
            onChange={(e) => setPlayerName(e.target.value)}
            placeholder="Enter your name"
            className="bg-slate-700/50 border-slate-600 text-white placeholder:text-white/50"
            disabled={isLoading}
            data-testid="player-name-input-create-test"
            onKeyDown={(e) => e.key === 'Enter' && playerName.trim() && !showJoinForm && onCreateRoom()}
          />
        </div>

        {!showJoinForm ? (
          <div className="space-y-4">
            <Button
              onClick={onCreateRoom}
              disabled={!playerName.trim() || isLoading}
              className="w-full h-12 bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white font-semibold text-lg"
              data-testid="create-room-test"
            >
              {isLoading ? (
                <div className="flex items-center gap-2">
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white" />
                  <span>Creating...</span>
                </div>
              ) : (
                <div className="flex items-center gap-2">
                  <PlayCircle className="w-5 h-5" />
                  <span>Create New Game</span>
                </div>
              )}
            </Button>

            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-white/20" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-slate-800 px-2 text-white/60">or</span>
              </div>
            </div>

            {/* Join Random Game Button */}
            {onJoinRandomRoom && (
              <Button
                onClick={onJoinRandomRoom}
                disabled={!playerName.trim() || isLoading}
                variant="outline"
                className="w-full h-12 border-purple-500/50 text-purple-400 hover:bg-purple-500/10"
                data-testid="join-random-game-test"
              >
                <Shuffle className="w-5 h-5 mr-2" />
                Join Random Game
              </Button>
            )}

            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-white/20" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-slate-800 px-2 text-white/60">or</span>
              </div>
            </div>

            <Button
              onClick={() => setShowJoinForm(true)}
              disabled={!playerName.trim() || isLoading}
              variant="outline"
              className="w-full h-12 border-blue-500/50 text-blue-400 hover:bg-blue-500/10"
              data-testid="show-join-form-test"
            >
              <Users className="w-5 h-5 mr-2" />
              Join with Code
            </Button>
          </div>
        ) : (
          <div className="space-y-4">
            <div>
              <Label htmlFor="roomId" className="text-white/90 mb-2 block">Room Code</Label>
              <Input
                id="roomId"
                type="text"
                value={roomId}
                onChange={(e) => setRoomId(e.target.value.toUpperCase())}
                placeholder="Enter 6-character code"
                className="bg-slate-700/50 border-slate-600 text-white placeholder:text-white/50 font-mono"
                maxLength={6}
                disabled={isLoading}
                data-testid="room-id-input-test"
                onKeyDown={(e) => e.key === 'Enter' && handleJoin()}
              />
            </div>
            <div className="flex gap-4">
              <Button
                onClick={() => setShowJoinForm(false)}
                variant="outline"
                className="flex-1 h-12 border-slate-600 text-white/80 hover:bg-slate-700/50"
                disabled={isLoading}
              >
                Back
              </Button>
              <Button
                onClick={handleJoin}
                disabled={!playerName.trim() || !roomId.trim() || isLoading}
                className="flex-1 h-12 bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white font-semibold"
                data-testid="join-room-submit-test"
              >
                {isLoading ? (
                  <div className="flex items-center gap-2">
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white" />
                    <span>Joining...</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-2">
                    <Users className="w-5 h-5" />
                    <span>Join Room</span>
                  </div>
                )}
              </Button>
            </div>
          </div>
        )}

        {error && (
          <div className="bg-red-500/20 border border-red-500/50 rounded-lg p-3 text-red-300 text-sm text-center">
            {error}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
